---
title: "Mini-Project 02"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_float: true
---

# Data Visualization Project 02

_revised version of mini-project 02 goes here_
Marathon results dataset imported instead of read_csv since it was included into data file of project folder

Unsure how to import shapefile through project so imported same way as mini project 2
```{r}
#install.packages("sf")
library(sf)
world_shapes <- read_sf( "C:/Users/hfort/OneDrive/Desktop/HF_dataviz_finproj/dataviz_final_project/data/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp")
```

```{r}
setwd('C:/Users/hfort/OneDrive/Desktop/HF_dataviz_finproj/dataviz_final_project/data')
marathon_results_2017 = read.csv("marathon_results_2017.csv")
#marathon_results_2017
#library(readr)
#marathon_results<-read.csv("C:/Users/hfort/OneDrive/Desktop/HF_dataviz_finproj/dataviz_final_project#/data/marathon_results_2017.csv")

```


```{r}
library(plotly)
library(dplyr)
library(tidyverse)
country_count <- marathon_results_2017 %>%
  group_by(Country) %>%
  mutate(count = n()) %>%
  ungroup() 
```

```{r}
country_count <- country_count %>%
  rename(ISO_A3 = Country)


world_marathon <-world_shapes %>%
  left_join(country_count, by = "ISO_A3")
```

```{r}
ggplot() +
  geom_sf(data = world_marathon, aes(fill = count)) +
  scale_fill_gradientn(colors = c("blue", "green", "yellow", "red")) +  # Adjust colors
  theme_light()
```
```{r}
marathon_results_2017$M.F<-as.factor(marathon_results_2017$M.F)
class(marathon_results_2017$M.F)
```

```{r}
top_100 <- marathon_results_2017 %>%
  filter(Overall <= 100)

interactive_plot<- ggplot(data= top_100, aes(x = Overall, y = Gender, color = M.F))+
  geom_point()+
  theme_light()

library(plotly)
ggplotly(interactive_plot)
```

```{r}
gender_box<-ggplot(marathon_results_2017, aes(x = M.F, y = Overall, fill = M.F)) +
  geom_boxplot() +
  theme_light()
library(plotly)
ggplotly(gender_box)
```
```{r}
gender_violin<-ggplot(marathon_results_2017, aes(x = M.F, y = Overall, fill = M.F)) +
  geom_violin(width = 0.5) +
  #geom_jitter(height = 0, size = 1, 
   #           alpha = 0.5) +
  labs(x = "", y = "Weight") +
  guides(color = FALSE) + 
  theme_minimal()
gender_violin
```
```{r}
ggsave(gender_violin, file="gender_violin.png", scale=2)
```


```{r}
regression_model <- lm(Overall ~ Age,
 data = marathon_results_2017)
ggplot(marathon_results_2017, aes(x = Age, y = Overall)) +
 geom_point() +
 geom_smooth(method = "lm",
 formula = "y ~ x") +
  theme_light()

```
```{r}
top_100 <- marathon_results_2017 %>%
  filter(Overall <= 100)

regression_model <- lm(Overall ~ Age,
 data = top_100)
ggplot(top_100, aes(x = Age, y = Overall)) +
 geom_point() +
 geom_smooth(method = "lm",
 formula = "y ~ x") +
   annotate(geom = "text",
 x = 37, y = 55,
 label = "Age clearly doesn't define fitness level!")+
  theme_light()

```
```{r}

```

